#ARG FUNCTION_DIR="/app"

FROM python:3-alpine3.15
WORKDIR /app
COPY . /app
#RUN pip install -r requirements.txt
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
EXPOSE 3000
CMD python ./app/main.py 
