# Generated by Django 4.2 on 2023-04-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('number_pedido', models.TextField(max_length=255)),
                ('assunto', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
